"""Remove found_slots table

Revision ID: 002
Revises: 001
Create Date: 2025-01-30 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем таблицу found_slots, так как теперь слоты не сохраняются в БД
    op.drop_index(op.f('ix_found_slots_monitoring_id'), table_name='found_slots')
    op.drop_index(op.f('ix_found_slots_id'), table_name='found_slots')
    op.drop_table('found_slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Восстанавливаем таблицу found_slots
    op.create_table('found_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=255), nullable=False),
    sa.Column('slot_date', sa.DateTime(), nullable=False),
    sa.Column('slot_time', sa.String(length=10), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('is_booked', sa.Boolean(), nullable=True),
    sa.Column('slot_info', sa.JSON(), nullable=True),
    sa.Column('found_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_id'], ['slot_monitoring.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_found_slots_id'), 'found_slots', ['id'], unique=False)
    op.create_index(op.f('ix_found_slots_monitoring_id'), 'found_slots', ['monitoring_id'], unique=False)
    # ### end Alembic commands ###






