"""Remove slots_found field from slot_monitoring

Revision ID: 003
Revises: 002
Create Date: 2025-01-30 17:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем поле slots_found из таблицы slot_monitoring
    op.drop_column('slot_monitoring', 'slots_found')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Восстанавливаем поле slots_found в таблице slot_monitoring
    op.add_column('slot_monitoring', sa.Column('slots_found', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###






