"""Add failed_booking_dates field to SlotMonitoring

Revision ID: 39229efd9b87
Revises: aac4f225e424
Create Date: 2025-09-25 16:01:20.201592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39229efd9b87'
down_revision = 'aac4f225e424'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot_monitoring', sa.Column('failed_booking_dates', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_monitoring', 'failed_booking_dates')
    # ### end Alembic commands ###
