"""add_phone_auth_fields

Revision ID: 710fdf902df0
Revises: e63f9809fb82
Create Date: 2025-09-16 11:58:21.481747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710fdf902df0'
down_revision = 'e63f9809fb82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('encrypted_wb_session', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('wb_inn', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('wb_seller_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_auth_created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('phone_auth_last_used_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_auth_last_used_at')
    op.drop_column('users', 'phone_auth_created_at')
    op.drop_column('users', 'wb_seller_name')
    op.drop_column('users', 'wb_inn')
    op.drop_column('users', 'encrypted_wb_session')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
