"""add_logistics_shoulder_to_slot_monitoring

Revision ID: 84d97e1fb3e8
Revises: 003
Create Date: 2025-09-10 16:11:59.173866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d97e1fb3e8'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot_monitoring', sa.Column('logistics_shoulder', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_monitoring', 'logistics_shoulder')
    # ### end Alembic commands ###
