"""add_order_number_to_slot_monitoring

Revision ID: aac4f225e424
Revises: 710fdf902df0
Create Date: 2025-09-22 18:58:53.303307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac4f225e424'
down_revision = '710fdf902df0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot_monitoring', sa.Column('order_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_monitoring', 'order_number')
    # ### end Alembic commands ###
