"""add_box_type_id_to_slot_monitoring

Revision ID: e63f9809fb82
Revises: 84d97e1fb3e8
Create Date: 2025-09-11 10:23:09.552292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63f9809fb82'
down_revision = '84d97e1fb3e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot_monitoring', sa.Column('box_type_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_monitoring', 'box_type_id')
    # ### end Alembic commands ###
